Algoritmo "bank"

Var
   ping:real
   dinheiro:real


Inicio

//    CLIENT PT-1

      escreva("Informe o valor que deseja depositar: ")
                       leia(dinheiro)

//    LOG CLIENT

      dinheiro<-(dinheiro)
      escreval("Dinheiro depositado, valor de: " ,dinheiro)

//    LOG DE SERVER

      dinheiro<-(dinheiro)
      escreval("Deposito recebido com sucesso, valor de: " ,dinheiro)

Fimalgoritmo