Algoritmo "identidade"

Var
          nome:caracter
          nascimento,ano,subtracao:inteiro

Inicio
      escreva("Informe seu nome ")
                       leia(nome)
      escreva("Informe o ano que você está ")
                       leia (ano)
      escreva("Informe o ano de seu nascimento ")
                       leia (nascimento)
                       
      subtracao<-(ano-nascimento)
      escreval("A sua idade é " ,subtracao)
                       
Fimalgoritmo